 
spring.datasource.primaryUrl=jdbc:postgresql://localhost:5432/events
server.port=8081
spring.datasource.primaryUsername=postgres
spring.datasource.primaryPassword=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.readUrl=jdbc:postgresql://localhost:5432/events
spring.datasource.readUsername=postgres
spring.datasource.readPassword=postgres
logging.level.org.springframework.web=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
event.kafka.consumer.bootstrap-servers: test:9092
event.kafka.consumer.group-id: group1
event.kafka.consumer.auto-offset-reset: latest
event.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
event.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
event.kafka.consumer.properties.spring.json.trusted.packages=*
event.kafka.producer.bootstrap-servers: test:9092
event.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
event.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
SERVICE_ENV=postgres
event.kafkaTopic = topic2
event.errorTopic=errorTopic
event.consumeTopic=topic3
#sever.port =9095
event.delay=6000
spring.data.redis.host=localhost
spring.data.redis.port=6379
CACHE_ENABLED=true
mongodb.enabled:false
doc.base.url:https://documentation.dev.flex83.com

