spring:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/events
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    read:
      url: jdbc:postgresql://localhost:5432/events
      username: postgres
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.web: DEBUG

event:
  kafka:
    consumer:
      bootstrap-servers: test:9092
      group-id: group1
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      bootstrap-servers: test:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  kafkaTopic: topic2
  errorTopic: errorTopic
  consumeTopic: topic3
  delay: 6000

CACHE_ENABLED: true
mongodb:
  enabled: false

doc:
  base:
    url: https://documentation.dev.flex83.com
